package primero;
// Generated 23-abr-2016 22:39:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

    private String nombre;
    private String ciudad;
    private String conferencia;
    private String division;
    private Set<Jugadores> jugadoreses = new HashSet<Jugadores>(0);
    private Set<Partidos> partidosesForEquipoVisitante = new HashSet<Partidos>(0);
    private Set<Partidos> partidosesForEquipoLocal = new HashSet<Partidos>(0);

    public Equipos() {
    }

    public Equipos(String nombre) {
        this.nombre = nombre;
    }

    public Equipos(String nombre, String ciudad, String conferencia, String division, Set<Jugadores> jugadoreses,
                   Set<Partidos> partidosesForEquipoVisitante, Set<Partidos> partidosesForEquipoLocal) {
        this.nombre = nombre;
        this.ciudad = ciudad;
        this.conferencia = conferencia;
        this.division = division;
        this.jugadoreses = jugadoreses;
        this.partidosesForEquipoVisitante = partidosesForEquipoVisitante;
        this.partidosesForEquipoLocal = partidosesForEquipoLocal;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getConferencia() {
        return this.conferencia;
    }

    public void setConferencia(String conferencia) {
        this.conferencia = conferencia;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    public Set<Jugadores> getJugadoreses() {
        return this.jugadoreses;
    }

    public void setJugadoreses(Set<Jugadores> jugadoreses) {
        this.jugadoreses = jugadoreses;
    }

    public Set<Partidos> getPartidosesForEquipoVisitante() {
        return this.partidosesForEquipoVisitante;
    }

    public void setPartidosesForEquipoVisitante(Set<Partidos> partidosesForEquipoVisitante) {
        this.partidosesForEquipoVisitante = partidosesForEquipoVisitante;
    }

    public Set<Partidos> getPartidosesForEquipoLocal() {
        return this.partidosesForEquipoLocal;
    }

    public void setPartidosesForEquipoLocal(Set<Partidos> partidosesForEquipoLocal) {
        this.partidosesForEquipoLocal = partidosesForEquipoLocal;
    }

}
